# Defines the options for building the project on linux with Travis-CI
# For more configuration options, see the wiki:
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
sudo: required
warnings_ar_errors: true

before_install:
  - wget http://downloads.sourceforge.net/project/mcmc-jags/JAGS/3.x/Source/JAGS-3.4.0.tar.gz
  - tar xfvs JAGS-3.4.0.tar.gz
  - cd JAGS-3.4.0
  - sudo ./configure
  - sudo make
  - sudo make install
  - cd ..

r_github_packages:
 - jimhester/covr
 - appling/unitted

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
