# Defines the options for building the project on Windows with ci.appveyor.com.
# For more configuration options, see https://www.appveyor.com/docs/build-configuration.
# Note that we're calling a customized version of appveyor-tool.ps1 to get R-stable
# and to call a customized version of travis-tool.sh which uses GRAN+CRAN by default.

environment:
  R_VERSION: 'patched'
  USE_RTOOLS: true
  R_CHECK_ARGS: --no-build-vignettes --no-manual --no-multiarch
  R_BUILD_ARGS: --no-build-vignettes --no-manual
  R_INSTALL_ARGS: --no-multiarch
  GITHUB_PAT: 
    secure: lWDip/KqkDcRmLEPjvsVSpQ7HJcSmE5HwyQVzDBJetaUdaYI1Us5tAs6E9K8kpSj

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/USGS-R/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - ps: (new-object net.webclient).DownloadFile("http://owi.usgs.gov/R/r-buildtools/JAGS-3.4.0.exe", "C:\projects\JAGS-3.4.0.exe")
  - cmd: C:\projects\JAGS-3.4.0.exe /S
  - cmd: dir "C:\Program Files\JAGS"

build_script:
  - R --version
  - travis-tool.sh install_github GLEON/LakeMetabolizer
  - travis-tool.sh install_deps
  - travis-tool.sh install_r modeest

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
